spring.application.name=Teacher_Application

spring.datasource.url=jdbc:mysql://mysql.railway.internal:3306/railway
spring.datasource.username=root
spring.datasource.password=axECqHBIHDCtpBwClQcHdkNGbVsbGUnZ

server.port=${PORT:6969}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.show_sql=true